# Generated by Django 2.2 on 2019-05-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='white', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=28)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='M', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('prating', models.IntegerField(default=0)),
                ('pshort_description', models.CharField(default='', max_length=300)),
                ('plong_description', models.CharField(default='', max_length=2000)),
                ('pmanufacturer', models.CharField(default='', max_length=2000)),
                ('pcolor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Color')),
                ('pimage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Image')),
                ('psize', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Size')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
